/**
 * PATISSERIE (Geert 2026-10-10: "add common patisserie foods, incl. bread pudding") — Belgian / Dutch / French bakery
 * items CIQUAL doesn't carry. GENERATED from scripts/food/patisserie.json (scripts/food/gen-patisserie.py) — edit the
 * JSON, not this file. Display names Dutch / English (French names only as search aliases). Sources: NEVO-Online 2025,
 * USDA SR Legacy, Belgian / Dutch product labels; recipe-based ESTIMATES are marked in each note.
 * Matching is FULL-ALIAS (`full`): "pudding" or "taart" alone never pulls these up — name the pastry.
 */
import type { SportsItem } from './foodSports';
import type { FoodItem } from './foodLog';

const p = (id: string, name: string, per100: FoodItem['per100'], g: number, label: string, aliases: string[], note: string): SportsItem =>
  ({ key: `builtin:pat_${id}`, src: 'builtin', id: `pat_${id}`, name, per100, serving: { g, label }, aliases, note, powder: false, full: true });

export const PATISSERIE_ITEMS: SportsItem[] = [
  p("bread_pudding_belgian", "Bread pudding (broodpudding)", { kcal: 203, prot: 5.7, carb: 31.2, sug: 19, fat: 5.9, sat: 3.1, fib: 1.1, na: 162, salt: 0.41 }, 110, "1 slice", ["broodpudding", "brood pudding", "pudding au pain", "bread pudding", "broodpudding met rozijnen"], "ESTIMATE: recipe-based (Flemish bakery broodpudding: 500 g stale white bread, 1 L whole milk, 4 eggs, 200 g brown sugar, 150 g raisins, 50 g butter, 12% baking loss; ingredient values NEVO/USDA generic). Cross-check: USDA FNDDS 13210110 \"Pudding, bread with raisins\" = 156 kcal (moister, less bread) - Belgian bakery slices are denser. · Serving: 1 slice (~110 g)."),
  p("bread_and_butter_pudding", "Bread and butter pudding", { kcal: 235, prot: 6, carb: 22.9, sug: 13.1, fat: 13, sat: 7.4, fib: 0.9, na: 146, salt: 0.36 }, 150, "1 portion", ["bread and butter pudding", "bread & butter pudding", "bread n butter pudding"], "ESTIMATE: recipe-based (UK classic: 180 g buttered white bread + 30 g butter, 3 eggs, 310 g whole milk, 150 g double/whipping cream, 50 g sugar, 50 g sultanas, 10% baking loss). Commercial UK range ~160-240 kcal/100 g (e.g. M&S label 240 kcal, F 15.1). · Serving: 1 portion (~150 g)."),
  p("rice_tart_belgian", "Rice tart (rijsttaart)", { kcal: 211, prot: 4.5, carb: 34.5, sug: 17.5, fat: 6, sat: 3, fib: 0.7, na: 262, salt: 0.66 }, 120, "1 tartlet or slice", ["rijsttaart", "rijsttaartje", "rijstetaart", "rijstevlaai", "rijstvlaai", "tarte au riz", "tartelette au riz", "rice tart", "rice flan"], "NEVO-Online 2025 9.0, code 489 \"Vlaai rijste-\" (Flan filled w rice pudding), Matches Belgian label Partout \"Rijsttaart stuk 120g\" (211 kcal, F 5.5, C 34.9, sugars 19). · Serving: 1 tartlet or slice (~120 g)."),
  p("sugar_tart_belgian", "Sugar tart (suikertaart)", { kcal: 357, prot: 5.5, carb: 60.7, sug: 43.3, fat: 10.4, sat: 6.6, fib: 1.5, na: 295, salt: 0.74 }, 80, "1 slice", ["suikertaart", "suiker taart", "tarte au sucre", "tarte au sucre brun", "tarte a la cassonade", "tarte au sucre et vergeoise", "sugar tart"], "Product label: Defroidmont (BE) \"Tarte au sucre et vergeoise\", per 100 g via Open Food Facts / informationsnutritionnelles.fr (1495 kJ). Fibre not declared -> 1.5 g estimated. · Serving: 1 slice (~80 g)."),
  p("mattentaart", "Mattentaart (Geraardsbergse mattentaart)", { kcal: 374, prot: 10.5, carb: 37.7, sug: 21.5, fat: 20.1, sat: 10.6, fib: 0.5, na: 300, salt: 0.75 }, 100, "1 tartlet", ["mattentaart", "mattentaartje", "geraardsbergse mattentaart", "tarte au maton", "tartelette au maton", "maton tart", "curd tart geraardsbergen"], "Product label: Partout \"Mattentaart stuk 115g\" (BE), PS in foodservice (salt 0.75 g -> Na 300 mg). Diversi Foods mattentaartje 115 g similar (388 kcal). · Serving: 1 tartlet (~100 g)."),
  p("frangipane_tartlet", "Frangipane tartlet (frangipanetaartje)", { kcal: 428, prot: 5.6, carb: 48.6, sug: 23.6, fat: 23.4, sat: 8.7, fib: 1.5, na: 270, salt: 0.68 }, 80, "1 tartlet", ["frangipanetaartje", "frangipane taartje", "frangipanetaart", "frangipane", "tartelette frangipane", "frangipane tartlet", "almond tartlet"], "Product labels, average of Molco \"Frangipanetaartje\" 80 g (puff pastry, frangipane, white icing) and Holeki \"Frangipane taartje rond\" (with apricot jam, fondant), PS in foodservice codes 1751441 / 1760461 · Serving: 1 tartlet (~80 g)."),
  p("merveilleux", "Meringue cream pastry", { kcal: 431, prot: 4.8, carb: 40, sug: 40, fat: 27, sat: 18, fib: 3.2, na: 56, salt: 0.14 }, 85, "1 individual", ["merveilleux", "merveilleux chocolat", "merveilleux au chocolat", "meringue cream cake", "meringue whipped cream pastry"], "Product label: Picard \"2 merveilleux au chocolat\" (175 g), per 100 g via Open Food Facts. Other labels 347-431 kcal (Casino 376). · Serving: 1 individual (~85 g)."),
  p("cramique", "Raisin brioche (kramiek)", { kcal: 332, prot: 7.4, carb: 57, sug: 19, fat: 7.7, sat: 3.6, fib: 2.7, na: 400, salt: 1 }, 40, "1 slice", ["kramiek", "cramique", "cramique aux raisins", "rozijnenbrioche", "raisin brioche"], "Product label: Delhaize (BE) \"Cramique\", per 100 g via Open Food Facts. NEVO 244 \"Tarwerozijnenbrood wit\" (272 kcal, F 2.7) is the leaner Dutch raisin bread. · Serving: 1 slice (~40 g)."),
  p("craquelin", "Sugar bread (suikerbrood)", { kcal: 360, prot: 6.7, carb: 65, sug: 27, fat: 7.5, sat: 3.7, fib: 2, na: 400, salt: 1 }, 40, "1 slice", ["suikerbrood", "craquelin", "craquelin brioche", "pearl sugar brioche", "sugar bread", "suikerbrood met parelsuiker"], "Product label: Belgian \"Mini Craquelins Frais\" per 100 g via Open Food Facts (fibre not declared -> 2.0 estimated). Note: Dutch Fries suikerbrood is leaner - NEVO 2355 \"Tarwesuikerbrood wit\" 306 kcal, F 3.0, sugars 28.5. · Serving: 1 slice (~40 g)."),
  p("liege_waffle", "Liège waffle (Luikse wafel)", { kcal: 446, prot: 5.7, carb: 57.1, sug: 29.5, fat: 21.3, sat: 9.7, fib: 1.5, na: 270, salt: 0.68 }, 90, "1 waffle", ["luikse wafel", "luikse wafels", "suikerwafel", "parelsuikerwafel", "gaufre de liege", "gaufre liegeoise", "liege waffle", "liège waffle", "pearl sugar waffle"], "NEVO-Online 2025 9.0, code 2661 \"Wafel Luikse-\" (average of O'Lacy, Albert Heijn, Lotus, Bellbake) · Serving: 1 waffle (~90 g; packaged ~55 g)."),
  p("brussels_waffle", "Brussels waffle (Brusselse wafel)", { kcal: 303, prot: 5.4, carb: 39, sug: 10.5, fat: 13.4, sat: 1.2, fib: 1, na: 195, salt: 0.49 }, 93, "1 waffle with icing sugar", ["brusselse wafel", "brusselse wafels", "gaufre de bruxelles", "gaufres de bruxelles", "brussels waffle", "belgian waffle plain", "wafel met poedersuiker"], "Product labels, average of Delhaize (BE), Carrefour \"Les Belges\" (BE) and Thiriet \"Gaufres de Bruxelles\" (via Open Food Facts) + ESTIMATE 8 g icing sugar per 85 g waffle. Street/bakery waffles made with butter will have more saturated fat. · Serving: 1 waffle with icing sugar (~93 g)."),
  p("berliner_custard", "Berliner with custard (berlinerbol)", { kcal: 293, prot: 5.3, carb: 44.4, sug: 18.9, fat: 10, sat: 3.1, fib: 1.7, na: 248, salt: 0.62 }, 90, "1 berliner", ["berlinerbol", "berliner bol", "berliner", "boule de berlin", "berliner met pudding", "berliner met banketbakkersroom", "custard doughnut", "cream filled doughnut"], "NEVO-Online 2025 9.0, code 1470 \"Berliner bol\", Belgian bakery versions with generous pastry cream can run ~300-350 kcal/100 g (AH label 346). · Serving: 1 berliner (~90 g)."),
  p("cinnamon_roll", "Cinnamon roll (kaneelbroodje)", { kcal: 342, prot: 5.4, carb: 42.5, sug: 16.8, fat: 16.2, sat: 8.2, fib: 1.8, na: 277, salt: 0.69 }, 100, "1 roll", ["kaneelbroodje", "kaneelbroodjes", "kaneelbol", "kaneelrol", "cinnamon roll", "cinnamon bun", "kanelbulle", "roule a la cannelle", "escargot cannelle"], "Product labels, average of glazed kaneelbroodje from Albert Heijn, Picnic, PLUS and Crisp (NL), via Open Food Facts. US-style cream-cheese-frosted bun is richer: USDA SR Legacy 18964 \"Cinnamon buns, frosted\" 452 kcal, F 26.6. · Serving: 1 roll (~100 g)."),
  p("pastel_de_nata", "Portuguese custard tart (pastel de nata)", { kcal: 272, prot: 4.4, carb: 38.7, sug: 17.9, fat: 10.9, sat: 5.3, fib: 1.5, na: 254, salt: 0.64 }, 65, "1 tart", ["pastel de nata", "pasteis de nata", "pastéis de nata", "pastel de belem", "portuguese custard tart", "portuguese egg tart"], "Product labels, average of 6 (Lidl, Gamberina, Polinorte PT, HMF, a Portuguese bakery entry, Pret) via Open Food Facts / pret.co.uk; fibre set to 1.5 (labels 0.9-4.0, median-ish). · Serving: 1 tart (~65 g)."),
  p("apple_strudel", "Apple strudel (appelstrudel)", { kcal: 274, prot: 3.3, carb: 41.1, sug: 25.8, fat: 11.2, sat: 2, fib: 2.2, na: 135, salt: 0.34 }, 120, "1 slice", ["appelstrudel", "apfelstrudel", "strudel aux pommes", "apple strudel", "appel strudel"], "USDA FoodData Central SR Legacy 18354 \"Strudel, apple\" (fdcId 175032). Butter-made bakery strudel has more saturated fat (USDA FNDDS 53440000: 281 kcal, sat 7.6). Not the Dutch appelcarre (NEVO 833). · Serving: 1 slice (~120 g)."),
  p("cupcake_buttercream", "Cupcake with buttercream", { kcal: 435, prot: 3.8, carb: 50.7, sug: 39.7, fat: 24.1, sat: 15.1, fib: 0.6, na: 292, salt: 0.73 }, 80, "1 cupcake", ["cupcake", "cupcakes", "cupcake met botercreme", "cupcake met boterroom", "cupcake buttercream", "vanilla cupcake"], "ESTIMATE: recipe-based (50 g butter sponge = NEVO 1969 \"Cake m roomboter\" + 30 g butter buttercream: 32% butter, 64% icing sugar, 4% milk). USDA FNDDS bakery cupcakes with white icing (53120270) = 359 kcal but use shortening-based icing. · Serving: 1 cupcake (~80 g)."),
  p("carrot_cake", "Carrot cake with cream-cheese frosting (worteltaart)", { kcal: 357, prot: 4.5, carb: 36.9, sug: 25.6, fat: 20.9, sat: 6.3, fib: 1.5, na: 220, salt: 0.55 }, 110, "1 slice", ["carrot cake", "carrotcake", "worteltaart", "wortelcake", "gateau aux carottes", "carrot cake cream cheese"], "NEVO-Online 2025 9.0, code 5254 \"Carrotcake\" (with walnuts and cream-cheese glaze) · Serving: 1 slice (~110 g)."),
  p("javanais", "Coffee butter-cream almond pastry", { kcal: 430, prot: 5.7, carb: 37.8, sug: 32.8, fat: 28.2, sat: 15.2, fib: 1.5, na: 88, salt: 0.22 }, 90, "1 individual pastry", ["javanais", "javanaisgebakje", "coffee buttercream cake", "gateau javanais"], "Product labels, average of 4 Belgian javanais (La Lorraine, Delhaize, Paul Gaelens artisanal, Holeki) via Open Food Facts; fibre set to 1.5 (labels 0.9-3.7). · Serving: 1 individual pastry (~90 g)."),
  p("miserable_cake", "Almond butter-cream cake", { kcal: 437, prot: 7.2, carb: 42.4, sug: 39, fat: 26.2, sat: 13.4, fib: 1.5, na: 61, salt: 0.15 }, 90, "1 individual pastry", ["miserable", "misérable", "miserable gebakje", "gateau miserable", "almond buttercream cake", "mini miserable"], "Product labels, average of 4 Belgian misérable (incl. Carrefour BE 125 g) via Open Food Facts; fibre set to 1.5 (only one label declared, 1.3). · Serving: 1 individual pastry (~90 g)."),
  p("religieuse", "Double cream puff, chocolate or coffee (dubbele soes)", { kcal: 265, prot: 4.4, carb: 30.9, sug: 21.1, fat: 13.5, sat: 7.9, fib: 1.2, na: 139, salt: 0.35 }, 110, "1 pastry", ["religieuse", "religieuse chocolat", "religieuse au chocolat", "religieuse cafe", "religieuse au cafe", "dubbele soes"], "Product labels, average of 5 chocolate religieuses (Tartefrais, Hafner, Patigel, La Campaniere, unbranded) via Open Food Facts; coffee version is equivalent within label spread. · Serving: 1 pastry (~110 g)."),
  p("pain_a_la_grecque", "Brussels Greek bread (Grieks brood)", { kcal: 409, prot: 7.3, carb: 70, sug: 45, fat: 10.8, sat: 7, fib: 1.5, na: 240, salt: 0.6 }, 65, "1 piece", ["pain a la grecque", "pain à la grecque", "grieks brood", "griekse brood", "brussels greek bread", "dandoy pain a la grecque"], "Product label: Maison Dandoy (Brussels) \"Pain a la grecque\", per 100 g via Open Food Facts. · Serving: 1 piece (~65 g)."),
];
